'use strict';

const ModelDocument = require('./ModelDocument');

/** Generates MySQL / MariaDB DDL from the physical model. */
class SqlDdlGenerator {
  static quote(name) {
    return `\`${String(name).replace(/`/g, '``')}\``;
  }

  generate(rawDocument) {
    const doc = ModelDocument.from(rawDocument);
    const q = SqlDdlGenerator.quote;
    const tables = doc.pdm.tables;
    const byId = new Map(tables.map((t) => [t.id, t]));
    const lines = [
      `-- ${doc.meta.name}`,
      `-- Generated by Modelizer Studio on ${new Date().toISOString()}`,
      'SET FOREIGN_KEY_CHECKS = 0;',
      ''
    ];

    tables.forEach((table) => {
      const defs = table.columns.map((c) => {
        const parts = [q(c.name), c.type || 'VARCHAR(100)'];
        parts.push(c.nullable && !c.pk ? 'NULL' : 'NOT NULL');
        if (c.autoIncrement) parts.push('AUTO_INCREMENT');
        return `  ${parts.join(' ')}`;
      });
      const pks = table.columns.filter((c) => c.pk).map((c) => q(c.name));
      if (pks.length) defs.push(`  PRIMARY KEY (${pks.join(', ')})`);
      lines.push(`DROP TABLE IF EXISTS ${q(table.name)};`);
      lines.push(`CREATE TABLE ${q(table.name)} (\n${defs.join(',\n')}\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;`, '');
    });

    tables.forEach((table) => {
      (table.indexes || []).forEach((index) => {
        const cols = index.columnIds.map((id) => table.columns.find((c) => c.id === id)).filter(Boolean).map((c) => q(c.name));
        if (!cols.length) return;
        const kind = index.type === 'unique' ? 'UNIQUE INDEX' : 'INDEX';
        lines.push(`CREATE ${kind} ${q(index.name)} ON ${q(table.name)} (${cols.join(', ')});`);
      });
    });

    lines.push('');
    doc.pdm.constraints.forEach((c) => {
      const from = byId.get(c.fromTableId);
      const to = byId.get(c.toTableId);
      const fromCols = c.fromIds.map((id) => from.columns.find((col) => col.id === id)).filter(Boolean);
      const toCols = c.toIds.map((id) => to.columns.find((col) => col.id === id)).filter(Boolean);
      if (!fromCols.length || fromCols.length !== toCols.length) return;
      lines.push(
        `ALTER TABLE ${q(from.name)} ADD CONSTRAINT ${q(c.name)} FOREIGN KEY (${fromCols.map((col) => q(col.name)).join(', ')}) `
        + `REFERENCES ${q(to.name)} (${toCols.map((col) => q(col.name)).join(', ')}) ON DELETE ${c.onDelete} ON UPDATE ${c.onUpdate};`
      );
    });
    lines.push('', 'SET FOREIGN_KEY_CHECKS = 1;', '');
    return lines.join('\n');
  }
}

module.exports = SqlDdlGenerator;
